basePath: /api/v1
definitions:
  github_com_FaintLocket424_rc-timing-api_internal_models.Driver:
    properties:
      car_class:
        type: string
      id:
        type: string
      name:
        type: string
      transponder:
        type: string
    type: object
  github_com_FaintLocket424_rc-timing-api_internal_models.Heat:
    properties:
      drivers:
        items:
          $ref: '#/definitions/github_com_FaintLocket424_rc-timing-api_internal_models.Driver'
        type: array
      id:
        type: string
      name:
        type: string
      results:
        items:
          $ref: '#/definitions/github_com_FaintLocket424_rc-timing-api_internal_models.RaceResult'
        type: array
      scheduled_at:
        type: string
      status:
        type: string
      type:
        description: Practice, Qualifying, Final
        type: string
    type: object
  github_com_FaintLocket424_rc-timing-api_internal_models.RaceResult:
    properties:
      laps:
        type: integer
      name:
        type: string
      pos:
        type: integer
      time:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: FaintLocket424
    url: https://github.com/FaintLocket424/rc-timing-api
  description: A web API for live RC timing data.
  title: RC Timing API
  version: "1.0"
paths:
  /live:
    get:
      description: Returns the currently active heat for the provided URL
      parameters:
      - description: Target Timing URL
        in: query
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_FaintLocket424_rc-timing-api_internal_models.Heat'
      summary: Get live race
      tags:
      - racing
swagger: "2.0"
