basePath: /api/v1
definitions:
  github_com_FaintLocket424_rc-timing-api_internal_models.DriverResultDTO:
    properties:
      best_lap:
        $ref: '#/definitions/time.Duration'
      car_number:
        type: integer
      driver_name:
        type: string
      position:
        type: integer
      race_time:
        $ref: '#/definitions/github_com_FaintLocket424_rc-timing-api_internal_models.RaceTimeDTO'
    type: object
  github_com_FaintLocket424_rc-timing-api_internal_models.HeatResultDTO:
    properties:
      best_lap:
        $ref: '#/definitions/time.Duration'
      class:
        type: string
      class_best_lap:
        $ref: '#/definitions/time.Duration'
      class_best_time:
        $ref: '#/definitions/github_com_FaintLocket424_rc-timing-api_internal_models.RaceTimeDTO'
      heat_number:
        type: integer
      results:
        items:
          $ref: '#/definitions/github_com_FaintLocket424_rc-timing-api_internal_models.DriverResultDTO'
        type: array
      round_number:
        type: integer
    type: object
  github_com_FaintLocket424_rc-timing-api_internal_models.RaceTimeDTO:
    properties:
      laps:
        type: integer
      race_time:
        $ref: '#/definitions/time.Duration'
    type: object
  time.Duration:
    enum:
    - -9223372036854775808
    - 9223372036854775807
    - 1
    - 1000
    - 1000000
    - 1000000000
    - 60000000000
    - 3600000000000
    format: int64
    type: integer
    x-enum-varnames:
    - minDuration
    - maxDuration
    - Nanosecond
    - Microsecond
    - Millisecond
    - Second
    - Minute
    - Hour
host: localhost:8080
info:
  contact:
    name: FaintLocket424
    url: https://github.com/FaintLocket424/rc-timing-api
  description: A web API for live RC timing data.
  title: RC Timing API
  version: "1.0"
paths:
  /event/practice/heat/{id}/round/{round_id}:
    get:
      description: Retrieves results for a specific practice heat and round using
        the target timing software.
      parameters:
      - description: Target Timing URL (URL-encoded)
        in: query
        name: url
        required: true
        type: string
      - description: 'Timing software type (default: bbk)'
        in: query
        name: software
        type: string
      - description: Heat Number
        in: path
        name: id
        required: true
        type: integer
      - description: Round Number
        in: path
        name: round_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_FaintLocket424_rc-timing-api_internal_models.HeatResultDTO'
        "400":
          description: Invalid Heat or Round ID
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Scraper or Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get practice heat results
      tags:
      - practice
swagger: "2.0"
